[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "openssl"]

[phases.install]
cmds = ["pnpm install --ignore-workspace --no-frozen-lockfile"]

[phases.build]
cmds = ["npx prisma generate", "npx tsc"]

[start]
cmd = "npx prisma db push --accept-data-loss && node dist/index.js"
